### ISSUE TITLE
any reason why `get`, `set` and `wrap` are let, and not const?

### ISSUE THREAD

**Issue by g-patel** [developit/histore#4]
Out of curiosity:
https://github.com/developit/histore/blob/333561ec6f3b0c971cd054df75ac1674d5e3a980/histore.js#L15

**Comment by g-patel** [comment]
Issued a [PR](https://github.com/developit/histore/pull/5)

**Comment by zenyr** [comment]
`'const'.length > 'let'.length === true` I guess? :)

**Comment by g-patel** [comment]
Haha

**Comment by developit** [comment]
Lol I'm only just accepting that everyone is going to make me use const :P
